### ISSUE TITLE
Python build

### ISSUE THREAD

**Issue by hoetmaaiers** [crosswalk-project/grunt-crosswalk#7]
Is the grunt crosswalk build based on the new python build script: https://crosswalk-project.org/documentation/getting_started/run_on_android.html ?

The documentation says it builds on top of **crosswalk-apk-generator** but that project is not actively maintained. 

If not, it would be cool to extend the grunt task to work with the python build script.

**Comment by davidmaxwaterman** [comment]
The python script is deprecated, and has been replaced with crosswalk-app-tools which is javascript so there is no need for the crosswalk-apk-generator since grunt-crosswalk should be able to require and call the latter directly. Currently, the API is a bit complex since focus was on making it easy for the command line. There is discussion on improving the API, but until then grunt-crosswalk will simply invoke the appropriate command line to package the app.
Closing.
